version: '3.8'

services:
    monara-api-dev:
        image: bhaktibuana/monara-api-dev:latest
        container_name: monara-api-dev
        restart: on-failure
        ports:
            - 4010:4010
        env_file:
            - ../.env.dev
        networks:
            - monara_api_dev_network

networks:
    monara_api_dev_network:
        name: monara_api_dev_network
